### PR TITLE
fix: webkit-appearance: none for ButtonContainer

### LINKED ISSUE #405: Button | Change -webkit-appearance to none to fix button anchors on Safari
For buttons with the `as` prop for the container changing it from a `button` to an `a`, keeps the role as `button` as expected, but safari forces button appearance to the anchor because of that role.

Fix is to set `-webkit-appearance: none;` on all button containers (we'll always want our styles)

Safari:
image

Chrome
image

### PR DESCRIPTION
**Pull request by asheerrizvi**
Closes #405

### CODE REVIEW

**Comment by aVileBroker** [comment]
@asheerrizvi you'll need to update your snapshots before pushing. You can run `yarn update-tests` to do that. Then commit the updated snapshot files.

**Comment by asheerrizvi** [comment]
@aVileBroker done.

**Review by aVileBroker — APPROVED** [review]

**Comment by aVileBroker** [comment]
Great, thanks so much for your contribution @asheerrizvi!

**Pull request merged**
