### PR TITLE
moved the location and export of checkboxTypes to match other enums - ag

### PR DESCRIPTION
**Pull request by agheadstorm**

### CODE REVIEW

**Review by aVileBroker — COMMENTED** [review]
Looks good - but you've got some conflicts

**Comment by agheadstorm** [comment]
I'm real confused on these merge conflicts there don't appear to be any when I'm looking at it locally

**Comment by aVileBroker** [comment]
Make sure your fork is up-to-date with the headstorm fork, that'll prob be why

**Comment by agheadstorm** [comment]
Moving this to another PR my branches got real out of sync

**Pull request closed without merging**
